### ISSUE TITLE
How to implement safe persistent plugin.

### ISSUE THREAD

**Issue by andriy-simonov** [castlabs/downstream_electron#116]
In the Simple Widevine DRM example there is UnsafeInMemoryPersistentPlugin implementation. What are requirements for the persistent plugin to be implemented in a safe way? Any references to specification, examples etc will be greatly appreciated.

**Comment by mackode** [comment]
Hey. I renamed the example plugin, so it is not that scary :) to `FakePersistentPlugin`. The name was given only to mark this is only temp storage.

EME standard describes a few requirements (and for application) about any session-related data (including Session Id):
- https://www.w3.org/TR/encrypted-media/#session-id
- https://www.w3.org/TR/encrypted-media/#session-storage
