### ISSUE TITLE
2.0.0: unhandled exception when internet connection is lost

### ISSUE THREAD

**Issue by jaredmcneill** [castlabs/downstream_electron#31]
When we go offline while a download is in progress, we usually see this unhandled exception dialog pop up a handful of times:

<img width="420" alt="downstream_electron_offline_error" src="https://user-images.githubusercontent.com/1992376/38510930-d9d69db2-3bfc-11e8-8c12-3e9e0232b377.png">

Short of catching and ignoring the error in the Node process's error handler, is there a better way to suppress this?

**Comment by obecny** [comment]
@jaredmcneill pls update to the latest version
