### ISSUE TITLE
mkdir syntax won't work in windows

### ISSUE THREAD

**Issue by andymartinwork** [castlabs/downstream_electron#5]
I noticed that the downloader attempts and fails to create these folders in windows:

With this example manifest:
https://content.uplynk.com/224ac8717e714b68831997ab6cea4015.mpd

C:\Users\rooda\github-clones\downstream_electron\public\movies\6343450905773342720/https://stgec-ausw.uplynk.com/80C078/
ausw/slices/224/4d24fd7483f048c181f0f874ca5db271/224ac8717e714b68831997ab6cea4015

It looks like the "folders" variable contains the contents of the BaseURL. In the examples, this is "dash", but in most cases it's a full URL which cannot be created as a subdirectory in windows.

**Comment by obecny** [comment]
fixed in https://github.com/castlabs/downstream_electron/pull/10
