### ISSUE TITLE
Wrong types in DownstreamElectronBE.configuration documentation

### ISSUE THREAD

**Issue by eugirdor** [castlabs/downstream_electron#69]
`offlineContentPortStart`, `maxOfflineContentPortRange`, and `numberOfManifestsInParallel` are all listed as being of type `string` in the documentation, but I believe they are all actually suppose to be `number`.

`customManifestIdFolderRegex` is listed as `string` and I think it should be `regex | string`

`closingTagForInvalidCustomManifestIdCharacter` is listed as `regex` and I think it should be `string`

https://castlabs.github.io/downstream_electron/DownstreamElectronBE.configuration.html

**Comment by mackode** [comment]
Hey, you're right. Thanks for contribution!
