### ISSUE TITLE
Crash when disconnecting from the network during an active download on Node 10

### ISSUE THREAD

**Issue by jaredmcneill** [castlabs/downstream_electron#96]
In Node 10 `domain.dispose()` has been removed, causing the error handler in `Downloads.start` to crash. You can trigger this by eg. disabling Wi-Fi on macOS while a download is active.

Removing the call to dispose makes the crash go away but I'm not sure if this is the correct fix for Node 10.

**Comment by mackode** [comment]
Tnx, fix is available in master.
