### ISSUE TITLE
cannot install using git+https://github.com/castlabs/downstream_electron.git#master

### ISSUE THREAD

**Issue by jeremco** [castlabs/downstream_electron#98]
Hi 

For our project, we are using a fork of downstream-electron : git+https://github.com/Orange-OpenSource/downstream_electron.git#develop

We are installing it using npm install  downstream-electron@git+https://github.com/Orange-OpenSource/downstream_electron.git#develop, to make some debug and some improvement. 

The problèm is that on windows, there is a problem since 0.3.5 version and prepack script. sed doesn't exist on windows .... We cannot install downstream anymore using this way

You can verify that the problem exists using npm install  downstream-electron@ git+https://github.com/castlabs/downstream_electron.git#master

>  npm install downstream-electron@git+https://github.com/castlabs/downstream_electron.git#master
> 
> > downstream-electron@0.3.5 prepack C:\Users\mwgk6681\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-3785d334
> > ./bin/prepack.sh
> 
> '.' n'est pas reconnu en tant que commande interne
> ou externe, un programme ex▒cutable ou un fichier de commandes.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> npm ERR! code ENOPACKAGEJSON

Jérémie

**Comment by jeremco** [comment]
Hi, I have tested your last modification, but it doesn't resolve my problem.

When we install downsteam using npm install 
git+https://github.com/castlabs/downstream_electron.git#master, the prepack and postpack scripts are called => we obtain a built library.

What we need and what we want is to clone only the repo, just like it was before.

Jérémie

**Comment by mackode** [comment]
Hi Jérémie,

Thank you for your input. 
If I understand your workflow correctly, the most harmful is `prepack` and `postpack` scripts?

I took the following versions to tests:
- `npm install downstream-electron@ git+https://github.com/castlabs/downstream_electron.git#0.1.1`
- `npm install downstream-electron@ git+https://github.com/castlabs/downstream_electron.git#v0.2.1`
- `npm install downstream-electron@ git+https://github.com/castlabs/downstream_electron.git#v0.2.6`
- `npm install downstream-electron@ git+https://github.com/castlabs/downstream_electron.git#v0.2.6`
- `npm install downstream-electron@ git+https://github.com/castlabs/downstream_electron.git#v0.3.2`

Only `npm install downstream-electron@ git+https://github.com/castlabs/downstream_electron.git#master` installs the working library, but in this case it does not get a library source, but a packed/built library, ready to use, with no patches.

When I use `npm install downstream-electron@git+https://github.com/Orange-OpenSource/downstream_electron.git#develop` it does download `api` directory and modified `package.json` which points to the main file `api/index.js`.

So what I would do:
- Use `prepack`/`postpack` only for building npm package
- npm package will hold only packed/built files and will point to `index.js`
- npm installed package from git repo will download `api` directory and will point to `api/index.js`

This will require changes in finding the forked child source file but should be feasible. 
Do you think it will solve your issue? (any other suggestions?)

Bartek

**Comment by mackode** [comment]
Hi Jérémie,

Please have a look at the current master and re-open if needed.

Bartek

**Comment by jeremco** [comment]
Hi @mackode 

Your modification solves the issue. Many thanks to you

Jérémie
